global:
  scrape_interval:     5s
  evaluation_interval: 15s 
  external_labels:
    monitor: 'nats-test-server'
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
scrape_configs:
  - job_name: 'nats-test-server'
    static_configs:
      - targets: ['nats-exporter:7777']
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
