name = "JuliaWorkerNative"
uuid = "6df88f02-ce11-4712-9e8c-fd3312ddd18e"
authors = ["Jakub Wronowski <jakubwro@gmail.com>"]
version = "0.1.0"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
NATS = "55e73f9c-eeeb-467f-b4cc-a633fde63d2a"
