# This file is machine-generated - editing it directly is not advised

julia_version = "1.9.3"
manifest_format = "2.0"
project_hash = "79f3990f29ec652a060e65ea3948c76b6f13afa5"

[[deps.Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[deps.Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"
